#!/usr/bin/env lua --FOR-LINTING-AND-FORMATTING-DON'T-RUN
-- This file is *not* meant to be ran or required. It's only lua for syntax highlighting.
error("You can't require the todo file!")

---TODO: Types for https://docs.gtk.org/gio/class.DBusConnection.html
